# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'masonry等间隔或等宽高排列多个控件' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for masonry等间隔或等宽高排列多个控件
    pod 'Masonry', '~> 1.1.0'
end
